#s3:
#  host: ""
#  bucket: ""
#  prefix: ""

log:
  level: debug

mikrotiks:
  - host: ""
    username: ""
    password: ""
    encryptionKey: ""
    downloadTo: "file:///tmp/" # s3://host/bucket/prefix/ file://local/path/
