log:
  level: warn

directory: ""

s3:
  host: ""
  accessKey: ""
  secretKey: ""
  region: ""
  path: ""
  usePathStyle: true

mikrotiks:
  - host: ""
    username: ""
    password: ""
    encryptionKey: ""
    # todo add labels for metadata
