#s3:
#  host: ""
#  bucket: ""
#  prefix: ""

mikrotiks:
  192.168.1.1:
    username: ""
    password: ""
    encryptionKey: ""
    downloadTo: "file:///tmp/" # s3://host/bucket/prefix/ file://local/path/
